"""Types for generating CDM input records."""

from datetime import datetime
from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, Field, FilePath

from jasentool.cdm.models.base import RWModel
from jasentool.cdm.models.enums import AnalysisSoftware, AnalysisType

from .manifest import URI

SCHEMA_VERSION: int = 2


class IgvAnnotationTrack(RWModel):
    """IGV annotation track data."""

    name: str  # track name to display
    format: str | None = None
    type: str  # track type
    uri: str  # path to the annotation file
    index_uri: str | None = None  # Optional path to the index


class CdmRecord(BaseModel):
    """Qc results container for CDM"""

    id: str
    software: AnalysisSoftware
    result: Any


CdmRecords: TypeAlias = list[CdmRecord]


class PipelineArtifact(BaseModel):
    """Describe a file generated by the pipeline."""

    software_name: AnalysisSoftware
    software_version: str
    uri: URI


class PipelineDefinition(BaseModel):
    """Static metadata about the pipeline code itself."""

    name: str
    version: str
    commit: str | None = None
    release_life_cycle: Literal["development", "validation", "staging", "production", "unknown"]


class PipelineRunConfig(BaseModel):
    """Configuration used for this specific execution."""

    command: str
    analysis_profile: list[str] = Field(default_factory=list)
    configuration_files: list[str] = Field(default_factory=list)


class PipelineInfo(BaseModel):
    """Full description of the pipeline and its execution."""

    definition: PipelineDefinition
    run_config: PipelineRunConfig
    artifacts: list[PipelineArtifact]


class PipelineRun(BaseModel):
    """Describe a execution of a pipeline."""

    pipeline_run_id: str
    assay: str
    executed_at: datetime
    pipeline_info: PipelineInfo


class SequencingInfo(BaseModel):
    """Information on the sample was sequenced."""

    sequencing_run_id: str
    platform: str
    instrument: str | None = None
    sequencing_method: str | None = None
    sequenced_at: datetime | None = None


class MinimalAnalysisRecord(BaseModel):
    """Minimal information about an analysis result."""

    software: str
    software_version: str
    uri: URI


class FullAnalysisResult(BaseModel):
    """Container for analysis results."""

    software: AnalysisSoftware
    software_version: str

    # how it was parsed
    parser_name: str
    parser_version: int
    parser_status: str
    reason: str | None = None

    # results
    analysis_type: AnalysisType
    results: Any


class GenericMetadataRecord(BaseModel):
    """Canonical internal representation of simple metadata values."""

    fieldname: str
    value: str | int | float | datetime
    category: str | None = None
    data_type: Literal["string", "integer", "float", "datetime"]


class TabularMetadataRecord(BaseModel):
    """Canonical internal representation of tabular metadata."""

    fieldname: str
    columns: list[str]
    rows: list[str] | None = None
    cells: list[list[Any]]
    category: str | None = None
    data_type: Literal["table"] = "table"


InternalMetadataRecord: TypeAlias = GenericMetadataRecord | TabularMetadataRecord


class InternalIndexArtifacts(BaseModel):
    """Index files generated by the pipeline."""

    ska_index: FilePath | None = None
    sourmash_signature: FilePath | None = None


class ParsedSampleResults(BaseModel):
    """Internal representation of a parsed sample."""

    schema_version: Literal[3] = 3

    sample_id: str
    sample_name: str
    lims_id: str

    groups: list[str] = Field(..., default_factory=list)

    # metadata
    metadata: list[InternalMetadataRecord] = Field(..., default_factory=list)
    sequencing: SequencingInfo
    pipeline: PipelineRun

    # reference info
    reference_genome_id: str | None = None
    annotation_tracks: list[IgvAnnotationTrack] = Field(..., default_factory=list)

    # analysis results and artifacts
    analysis_results: list[FullAnalysisResult | MinimalAnalysisRecord] = Field(
        ..., default_factory=list
    )
    index_artifacts: InternalIndexArtifacts | None = None
